### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by jtgd** [kautsig/org-weather#6]
How do I get Fahrenheit?

**Comment by jtgd** [comment]
I did this mod but it would be nice to integrate it better.

`(defun org-weather-temp (temperature field)
  "Extracts a given field element from a 'temp' element"
  (+ (/ (* (cdr (assoc field temperature)) 9) 5) 32))
`

**Comment by jtgd** [comment]
NVM above, this seems to be the way:

;; The api url, no need to change ususally
;;(defvar org-weather-api-url "http://api.openweathermap.org/data/2.5/forecast/daily?q=%s&mode=json&units=metric&cnt=7&APPID=%s")
(defvar org-weather-api-url "http://api.openweathermap.org/data/2.5/forecast/daily?q=%s&mode=json&units=imperial&cnt=7&APPID=%s")

**Comment by kautsig** [comment]
Hi jtgd,

thanks for your efforts. To clarify this for new users I added it to the README, because it was also asked in #5 already.

Regards,
chris
